apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-bff
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aman-jalan/argocd-test-repo.git
    path: guestbook/bff
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
